from Tools_def import *

TOOL_API_MAP = {
    "Satellite Image Semantic Segmentation Tool": Satellite_Image_Semantic_Segmentation_Tool,
    "Satellite Image Object Detection Tool": Satellite_Image_Object_Detection_Tool,
    "Area Estimator": Area_Estimator,
    "Building Footprint Extractor": Building_Footprint_Extractor,
    "Building Height Extractor": Building_Height_Extractor,
    "Road Network Extractor": Road_Network_Extractor,
    "Satellite Image Automatic Description Generator": Satellite_Image_Automatic_Description_Generator,
    "Satellite Image Land Use Inference Tool": Land_Use_Inference_Tool,
    "Structure Layout Analyzer": Structure_Layout_Analyzer,
    "Image Style Classifier": Image_Style_Classifier,
    "Building Density Estimator": Building_Density_Estimator,
    "Factory Recognizer": Factory_Recognizer,
    "Large Parking Area Detector": Large_Parking_Area_Detector,
    "Special Target Recognizer": Special_Target_Recognizer,
    "Street Object Detector": Street_Object_Detector,
    "Street View Semantic Segmentation Tool": Street_View_Semantic_Segmentation_Tool,
    "Building Facade Extractor": Building_Facade_Extractor,
    "Text Sign OCR": Text_Sign_OCR,
    "Building Type Cue Detector": Building_Type_Cue_Detector,
    "Vehicle Type Classifier": Vehicle_Type_Classifier,
    "Pedestrian Density Estimator": Pedestrian_Density_Estimator,
    "Street View Image Captioner": Street_View_Image_Captioner,
    "Building Function Inference Tool": Building_Function_Inference_Tool,
    "Street Scene Category Inference": Street_Scene_Category_Inference,
    "Infrastructure Detector": Infrastructure_Detector,
    "Object Count Reporter": Object_Count_Reporter,
    "Height Approximation Tool": Height_Approximation_Tool,
    "Commercial Clue Extractor": Commercial_Clue_Extractor,
    "Enclosure Detector": Enclosure_Detector,
    "Street View Architectural Feature Extractor":Street_View_Architectural_Feature_Extractor,
    "Street View Ground Level Detail Recognizer":Street_View_Ground_Level_Detail_Recognizer,
    "Satellite Image Roof and Building Footprint Detailer":Satellite_Image_Roof_and_Building_Footprint_Detailer,
    "Satellite Image Landmark Extraction Tool":Satellite_Image_Landmark_Extraction_Tool,
    "Street View Architectural Style Classifier":Street_View_Architectural_Style_Classifier,
    "Street View Architectural Feature Extractor":Street_View_Architectural_Feature_Extractor,
    "Satellite Image Railway Detector":Satellite_Image_Railway_Detector,
    "Satellite Image Geospatial Named Entity Extractor":Satellite_Image_Geospatial_Named_Entity_Extractor,
    "Vegetation Detector":Vegetation_Detector,
    "Satellite Image Geo-Region Localizer":Satellite_Image_Geo_Region_Localizer,
    "Satellite Image Waterfront Proximity Analyzer":Satellite_Image_Waterfront_Proximity_Analyzer,
    "Urban Block Morphology Classifier":Urban_Block_Morphology_Classifier,
}

    # "Satellite Image Super Resolution Tool": super_res_function,